name: Deploy to GitHub Pages

# Controls when the workflow will run
on:
  push:
    branches: ["complete"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Need to give GITHUB_TOKEN write access to deploy site
    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: complete

      - name: Generate static files
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm ci

      - run: npm run build

      - run: pwd
      - run: ls build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          allow_empty_commit: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
